use std::{fs, path::Path};

fn main() {
    let assets_dir = Path::new("assets");
    if !assets_dir.exists() {
        fs::create_dir_all(assets_dir).expect("Failed to create assets directory");
    }

    let tailwind_path = Path::new("assets/tailwind.css");
    if !tailwind_path.exists() {
        fs::write(
            tailwind_path,
            "/*
Generated by `build.rs`
This file should be replaced with actual Tailwind styles.
*/\n",
        )
        .expect("Could not create tailwind placeholder");
    }
}
