services:
  frontend:
    build: ./frontend
    networks:
      - backend
  backend:
    build: ./backend
    networks:
      - backend
      - db
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    networks:
      - db

networks:
  backend:
  db:
