//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::calendar::Entity as Calendar;
pub use super::instance_setting::Entity as InstanceSetting;
pub use super::user::Entity as User;
